import { NextRequest, NextResponse } from 'next/server'
import { createServiceClient } from '@/lib/supabase'

const TENANT_ID = '00000000-0000-0000-0000-000000000001'

// GET /api/loads              — board view (unarchived only)
// GET /api/loads?history=1    — all loads for history tab
// GET /api/loads?paid=true&settled=false  — settlements queue
export async function GET(req: NextRequest) {
  const supabase = createServiceClient()
  const { searchParams } = req.nextUrl
  const history  = searchParams.get('history') === '1'
  const paid     = searchParams.get('paid')
  const settled  = searchParams.get('settled')
  const search   = searchParams.get('q') ?? ''

  // Settlements queue: paid=true, settled=false
  // Settlements history: paid=true, settled=true
  const isSettlements = paid === 'true' && settled === 'false'
  const isSettledHistory = paid === 'true' && settled === 'true'
  const needsFinancials = isSettlements || isSettledHistory

  let query = supabase
    .from('loads')
    .select(`
      *,
      owner_operator:owner_operators(id, name, company_name, phone_whatsapp, dispatch_fee_pct),
      driver:drivers(id, name, phone_whatsapp),
      unit:units(id, unit_number, make, model, license_plate, license_plate_mx),
      stops(id, stop_type, sequence, city, state, appointment_at),
      deductions(id, description, amount, type)${needsFinancials ? `,\n      load_drivers(id, driver_id, driver_name, miles, rate_per_mile, total_pay, sort_order)` : ''}
    `)
    .eq('tenant_id', TENANT_ID)
    .order('created_at', { ascending: false })

  if (isSettlements) {
    query = query.eq('paid_ok', true).eq('settled_ok', false)
  } else if (isSettledHistory) {
    query = query.eq('settled_ok', true)
  } else if (!history) {
    // Board: only active (not archived) loads
    query = query.is('archived_at', null)
  }

  if (search) {
    query = query.or(
      `load_number.ilike.%${search}%,work_order_number.ilike.%${search}%,broker_name.ilike.%${search}%,bol_number.ilike.%${search}%`
    )
  }

  const { data, error } = await query
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(data)
}

// POST /api/loads  — create new load
export async function POST(req: NextRequest) {
  const supabase = createServiceClient()
  const body = await req.json()

  // Remove load_number from body — auto-generated by DB sequence
  const { load_number: _ignored, ...rest } = body

  const payload = {
    ...rest,
    tenant_id: TENANT_ID,
    trip_status: rest.trip_status ?? 'open',
    rate_con_ok:  false,
    pod_ok:       false,
    invoiced_ok:  false,
    paid_ok:      false,
    settled_ok:   false,
  }

  const { data, error } = await supabase
    .from('loads')
    .insert(payload)
    .select(`
      *,
      owner_operator:owner_operators(id, name, company_name, phone_whatsapp),
      driver:drivers(id, name, phone_whatsapp),
      unit:units(id, unit_number)
    `)
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(data, { status: 201 })
}
