import { NextRequest, NextResponse } from 'next/server'
import { createServiceClient } from '@/lib/supabase'

const TENANT_ID = '00000000-0000-0000-0000-000000000001'

export async function GET(req: NextRequest) {
  const sb = createServiceClient()
  const { searchParams } = req.nextUrl
  const status = searchParams.get('status') // 'pending' | 'paid' | 'overdue' | 'all'
  const q      = searchParams.get('q') ?? ''

  let query = sb
    .from('invoices')
    .select(`*, load:load_id(id, load_number, work_order_number, trip_status, pickup_date, delivery_date)`)
    .eq('tenant_id', TENANT_ID)
    .order('created_at', { ascending: false })

  if (status === 'pending') query = query.in('status', ['draft','sent'])
  else if (status === 'paid')    query = query.eq('status', 'paid')
  else if (status === 'overdue') query = query.eq('status', 'overdue')

  if (q) query = query.or(`invoice_number.ilike.%${q}%,broker_name.ilike.%${q}%`)

  // Auto-mark overdue
  await sb.from('invoices')
    .update({ status: 'overdue' })
    .eq('tenant_id', TENANT_ID)
    .in('status', ['sent'])
    .lt('due_at', new Date().toISOString().slice(0, 10))

  const { data, error } = await query
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(data)
}

export async function POST(req: NextRequest) {
  const sb   = createServiceClient()
  const body = await req.json()

  // Auto-set due_at from issued_at + payment_terms
  let due_at = body.due_at
  if (!due_at && body.issued_at && body.payment_terms) {
    const d = new Date(body.issued_at)
    d.setDate(d.getDate() + parseInt(body.payment_terms))
    due_at = d.toISOString().slice(0, 10)
  }

  const payload = { ...body, tenant_id: TENANT_ID, due_at, status: body.status ?? 'draft' }
  delete payload.invoice_number  // auto-generated by DB sequence

  const { data, error } = await sb.from('invoices').insert(payload).select().single()
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  // Mark load as invoiced
  if (payload.load_id) {
    await sb.from('loads').update({ invoiced_ok: true }).eq('id', payload.load_id)
  }

  return NextResponse.json(data, { status: 201 })
}
